# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Addtowallet' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'addtowallet' do
    @driver.get('http://localhost:3000/en')
    @driver.find_element(:link_text, 'Log in').click
    @driver.find_element(:id, 'username').click
    @driver.find_element(:id, 'username').send_keys('test2user')
    @driver.find_element(:id, 'password').click
    @driver.find_element(:id, 'password').send_keys('passwordtestuser')
    @driver.find_element(:id, 'password').send_keys(:enter)
    @driver.find_element(:name, 'commit').click
    @driver.find_element(:link_text, 'User: test2user').click
    prev_balance = @driver.find_element(:css, 'p:nth-child(4)').text[9..15].to_f+555
    @driver.find_element(:id, 'money').click
    @driver.find_element(:id, 'money').send_keys('555')
    @driver.find_element(:name, 'commit').click
    expect(@driver.find_element(:css, 'p:nth-child(4)').text[9..15].to_f).to eq(prev_balance)
    @driver.find_element(:link_text, 'Log out').click
  end
end
