# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Bookroom' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'bookroom' do
    @driver.get('http://localhost:3000/en')
    @driver.find_element(:link_text, 'Log in').click
    @driver.find_element(:id, 'username').click
    @driver.find_element(:id, 'username').send_keys('test2user')
    @driver.find_element(:id, 'password').click
    @driver.find_element(:id, 'password').send_keys('passwordtestuser')
    @driver.find_element(:name, 'commit').click
    @driver.find_element(:link_text, 'Check rooms').click
    @driver.find_element(:link_text, 'Check room').click
    @driver.find_element(:id, 'date').click
    @driver.find_element(:id, 'date').send_keys('2022-12-25')
    @driver.find_element(:name, 'commit').click
    expect(@driver.find_element(:css, 'div:nth-child(4)').text).to eq('hotel1: Room:newroom800 Date:2022-12-25 Unbook')
    @driver.find_element(:link_text, 'Unbook').click
    @driver.find_element(:link_text, 'Log out').click
  end
end
