# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Bookroom' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'bookroom' do
    @driver.get('http://localhost:3000/en')
    @driver.find_element(:link_text, 'Log in').click
    @driver.find_element(:id, 'username').click
    @driver.find_element(:id, 'username').send_keys('test2user')
    @driver.find_element(:id, 'password').click
    @driver.find_element(:id, 'password').send_keys('passwordtestuser')
    @driver.find_element(:name, 'commit').click
    @driver.find_element(:link_text, 'Check rooms').click
    @driver.find_element(:link_text, 'Check room').click
    @driver.find_element(:css, 'li:nth-child(28) > .active').click
    @driver.find_element(:name, 'commit').click
    expect(@driver.find_element(:css, 'td:nth-child(4)').text).to eq('2023-01-20')
    expect(@driver.find_element(:css, 'td:nth-child(3)').text).to eq('newroom800')
    expect(@driver.find_element(:css, 'td:nth-child(2)').text).to eq('hotel1')
    @driver.find_element(:link_text, '❌').click
    @driver.find_element(:link_text, 'Log out').click
  end
end
