# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Bookroomdublicate' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  after(:each) do
    @driver.find_element(:link_text, 'Log in').click
    @driver.find_element(:id, 'username').click
    @driver.find_element(:id, 'username').send_keys('admin')
    @driver.find_element(:id, 'password').click
    @driver.find_element(:id, 'password').send_keys('12345678')
    @driver.find_element(:name, 'commit').click
    @driver.find_element(:link_text, 'User: admin').click
    @driver.find_element(:link_text, '❌').click
    @driver.find_element(:link_text, 'Log out').click
    @driver.quit
  end
  it 'bookroomdublicate' do
    @driver.get('http://localhost:3000/')
    @driver.find_element(:link_text, 'Log in').click
    @driver.find_element(:id, 'username').click
    @driver.find_element(:id, 'username').send_keys('admin')
    @driver.find_element(:id, 'password').click
    @driver.find_element(:id, 'password').send_keys('12345678')
    @driver.find_element(:name, 'commit').click
    @driver.find_element(:link_text, 'Check rooms').click
    @driver.find_element(:link_text, 'Check room').click
    @driver.find_element(:id, 'datefield').click
    @driver.find_element(:id, 'datefield').send_keys('2023-04-28')
    @driver.find_element(:name, 'commit').click
    @driver.find_element(:link_text, 'Log out').click
    @driver.find_element(:link_text, 'Log in').click
    @driver.find_element(:id, 'username').click
    @driver.find_element(:id, 'username').send_keys('test2user')
    @driver.find_element(:id, 'password').click
    @driver.find_element(:id, 'password').send_keys('passwordtestuser')
    @driver.find_element(:name, 'commit').click
    @driver.find_element(:link_text, 'Check rooms').click
    @driver.find_element(:link_text, 'Check room').click
    @driver.find_element(:id, 'datefield').click
    @driver.find_element(:id, 'datefield').send_keys('2023-04-28')
    @driver.find_element(:name, 'commit').click
    expect(@driver.find_element(:css, '.alert').text).to eq('This room has already been taken')
    @driver.find_element(:link_text, 'Log out').click
  end
end
