# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Createandcheckhotel' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'createandcheckhotel' do
    @driver.get('http://localhost:3000/')
    @driver.find_element(:link_text, 'Log in').click
    @driver.find_element(:id, 'username').click
    @driver.find_element(:id, 'username').send_keys('admin')
    @driver.find_element(:id, 'password').click
    @driver.find_element(:id, 'password').send_keys('12345678')
    @driver.find_element(:name, 'commit').click
    @driver.find_element(:link_text, 'New hotel').click
    @driver.find_element(:id, 'hotel_location').click
    @driver.find_element(:id, 'hotel_location').send_keys('someadress')
    @driver.find_element(:id, 'hotel_name').click
    @driver.find_element(:id, 'hotel_name').send_keys('somename')
    @driver.find_element(:id, 'hotel_description').click
    @driver.find_element(:id, 'hotel_description').send_keys('some description of hotel')
    @driver.find_element(:id, 'hotel_image').send_keys("#{Rails.root}/spec/support/assets/images/hotels/istockphoto-104731717-612x612.jpg")
    @driver.find_element(:name, 'commit').click
    expect(@driver.find_element(:css, '.card-title').text).to eq('somename')
    expect(@driver.find_element(:css, '.card-text:nth-child(3)').text).to eq('some description of hotel')
    @driver.find_element(:css, '.btn:nth-child(2)').click
    @driver.find_element(:link_text, 'Log out').click
  end
end
