# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Deletinguser' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'deletinguser' do
    @driver.get('http://localhost:3000/en')
    @driver.find_element(:link_text, 'Register').click
    @driver.find_element(:id, 'user_username').click
    @driver.find_element(:id, 'user_username').send_keys('testuser')
    @driver.find_element(:id, 'user_password').click
    @driver.find_element(:id, 'user_password').send_keys('12345678')
    @driver.find_element(:id, 'user_email').click
    @driver.find_element(:id, 'user_email').send_keys('mail@gmail.com')
    @driver.find_element(:css, 'body').click
    @driver.find_element(:name, 'commit').click
    @driver.find_element(:id, 'username').click
    @driver.find_element(:id, 'username').send_keys('testuser')
    @driver.find_element(:id, 'password').click
    @driver.find_element(:id, 'password').send_keys('12345678')
    @driver.find_element(:name, 'commit').click
    @driver.find_element(:link_text, 'User: testuser').click
    @driver.find_element(:id, 'deleteuser').click
    @driver.find_element(:link_text, 'Log in').click
    @driver.find_element(:id, 'username').click
    @driver.find_element(:id, 'username').send_keys('testuser')
    @driver.find_element(:id, 'password').click
    @driver.find_element(:id, 'password').send_keys('12345678')
    @driver.find_element(:name, 'commit').click
    expect(@driver.find_element(:css, '.alert').text).to eq('Incorrect username or password')
    @driver.find_element(:link_text, 'Hotels').click
  end
end
