# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Dublicateuser' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'dublicateuser' do
    @driver.get('http://localhost:3000/en/sessions/new')
    @driver.find_element(:link_text, 'Register').click
    @driver.find_element(:id, 'user_username').click
    @driver.find_element(:id, 'user_username').send_keys('test2user')
    @driver.find_element(:id, 'user_password').click
    @driver.find_element(:id, 'user_password').send_keys('12345678')
    @driver.find_element(:id, 'user_email').click
    @driver.find_element(:id, 'user_email').send_keys('mail@gmail.com')
    @driver.find_element(:css, 'body').click
    @driver.find_element(:name, 'commit').click
    expect(@driver.find_element(:css, '.alert').text).to eq('Username has already been taken')
    @driver.find_element(:link_text, 'Hotels').click
  end
end
