# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Edithotel' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'edithotel' do
    @driver.get('http://localhost:3000/')
    @driver.find_element(:link_text, 'Log in').click
    @driver.find_element(:id, 'username').click
    @driver.find_element(:id, 'username').send_keys('admin')
    @driver.find_element(:id, 'password').click
    @driver.find_element(:id, 'password').send_keys('12345678')
    @driver.find_element(:name, 'commit').click
    @driver.find_element(:link_text, 'Check rooms').click
    @driver.find_element(:link_text, 'Edit hotel').click
    @driver.find_element(:id, 'hotel_name').click
    @driver.action.key_down(:left_control).send_keys('a').key_up(:left_control).perform
    @driver.action.send_keys(:delete).perform
    @driver.find_element(:id, 'hotel_name').send_keys("hotel2")
    @driver.find_element(:id, 'hotel_location').click
    @driver.action.key_down(:left_control).send_keys('a').key_up(:left_control).perform
    @driver.action.send_keys(:delete).perform
    @driver.find_element(:id, 'hotel_location').send_keys("somewhere2")
    @driver.find_element(:css, 'div:nth-child(5) > label').click
    @driver.find_element(:id, 'hotel_description').click
    @driver.action.key_down(:left_control).send_keys('a').key_up(:left_control).perform
    @driver.action.send_keys(:delete).perform
    @driver.find_element(:id, 'hotel_description').send_keys("not very descriptive description on hotel2")
    @driver.find_element(:css, 'body').click
    @driver.find_element(:name, 'commit').click
    expect(@driver.find_element(:css, '.card:nth-child(1) .card-title').text).to eq("hotel2")
    expect(@driver.find_element(:css, '.text-muted').text).to eq("somewhere2")
    expect(@driver.find_element(:css, '.card:nth-child(1) .card-text:nth-child(3)').text).to eq("not very descriptive description on hotel2")
    @driver.find_element(:link_text, 'Edit hotel').click
    @driver.find_element(:id, 'hotel_name').click
    @driver.action.key_down(:left_control).send_keys('a').key_up(:left_control).perform
    @driver.action.send_keys(:delete).perform
    @driver.find_element(:id, 'hotel_name').send_keys("hotel1")
    @driver.find_element(:id, 'hotel_location').click
    @driver.action.key_down(:left_control).send_keys('a').key_up(:left_control).perform
    @driver.action.send_keys(:delete).perform
    @driver.find_element(:id, 'hotel_location').send_keys("somewhere")
    @driver.find_element(:css, 'div:nth-child(5) > label').click
    @driver.find_element(:id, 'hotel_description').click
    @driver.action.key_down(:left_control).send_keys('a').key_up(:left_control).perform
    @driver.action.send_keys(:delete).perform
    @driver.find_element(:id, 'hotel_description').send_keys("not very descriptive description on hotel")
    @driver.find_element(:css, 'body').click
    @driver.find_element(:name, 'commit').click
    expect(@driver.find_element(:css, '.card:nth-child(1) .card-title').text).to eq("hotel1")
    expect(@driver.find_element(:css, '.text-muted').text).to eq("somewhere")
    expect(@driver.find_element(:css, '.card:nth-child(1) .card-text:nth-child(3)').text).to eq("not very descriptive description on hotel")
    @driver.find_element(:link_text, 'Log out').click
  end
end
