# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Incorrectroom' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'incorrectroom' do
    @driver.get('http://localhost:3000/')
    @driver.find_element(:link_text, 'Log in').click
    @driver.find_element(:id, 'username').click
    @driver.find_element(:id, 'username').send_keys('admin')
    @driver.find_element(:id, 'password').click
    @driver.find_element(:id, 'password').send_keys('12345678')
    @driver.find_element(:name, 'commit').click
    @driver.find_element(:link_text, 'Check rooms').click
    @driver.find_element(:link_text, 'New room').click
    @driver.find_element(:id, 'room_name').click
    @driver.find_element(:id, 'room_name').send_keys('rom')
    @driver.find_element(:id, 'room_description').click
    @driver.find_element(:id, 'room_description').send_keys('desc')
    @driver.find_element(:id, 'room_cost_per_night').click
    @driver.find_element(:id, 'room_cost_per_night').send_keys('-5')
    @driver.find_element(:name, 'commit').click
    expect(@driver.find_element(:css, '.alert:nth-child(2)').text).to eq('Description is too short (minimum is 25 characters)')
    expect(@driver.find_element(:css, '.alert:nth-child(3)').text).to eq('Name is too short (minimum is 4 characters)')
    expect(@driver.find_element(:css, '.alert:nth-child(4)').text).to eq('Cost per night must be greater than or equal to 0')
    expect(@driver.find_element(:css, '.alert:nth-child(5)').text).to eq('Images can\'t be blank')
    @driver.find_element(:link_text, 'Log out').click
  end
end
