# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Incorrecthotel' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'incorrecthotel' do
    @driver.get('http://localhost:3000/')
    @driver.find_element(:link_text, 'Log in').click
    @driver.find_element(:id, 'username').click
    @driver.find_element(:id, 'username').send_keys('admin')
    @driver.find_element(:id, 'password').click
    @driver.find_element(:id, 'password').send_keys('12345678')
    @driver.find_element(:name, 'commit').click
    @driver.find_element(:link_text, 'New hotel').click
    @driver.find_element(:id, 'hotel_location').click
    @driver.find_element(:id, 'hotel_location').send_keys('adr')
    @driver.find_element(:css, 'body').click
    @driver.find_element(:id, 'hotel_name').click
    @driver.find_element(:id, 'hotel_name').send_keys('nm')
    @driver.find_element(:id, 'hotel_description').click
    @driver.find_element(:id, 'hotel_description').send_keys('desc')
    @driver.find_element(:name, 'commit').click
    expect(@driver.find_element(:css, '.alert:nth-child(2)').text).to eq('Location is too short (minimum is 4 characters)')
    expect(@driver.find_element(:css, '.alert:nth-child(3)').text).to eq('Name is too short (minimum is 4 characters)')
    expect(@driver.find_element(:css, '.alert:nth-child(4)').text).to eq('Description is too short (minimum is 25 characters)')
    expect(@driver.find_element(:css, '.alert:nth-child(5)').text).to eq('Image can\'t be blank')
    @driver.find_element(:link_text, 'Log out').click
  end
end
